require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'BFA' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-google-cast/NoBluetooth', path: '../node_modules/react-native-google-cast/ios/'
  pod 'google-cast-sdk-no-bluetooth'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-fitness', :path => '../node_modules/@ovalmoney/react-native-fitness'

  target 'BFATests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.74.0' })
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      puts "Excluding arm64 sdk for iphone simulator"
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
    flipper_post_install(installer)
  end
end

target 'BFA-tvOS' do
  # Pods for BFA-tvOS

  target 'BFA-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
